# fly.toml app configuration file generated for lynkswap-indexer on 2024-06-03T04:05:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lynkswap-indexer'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3006
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
